version: '3.9'

services:
  postgres:
    container_name: local_tomcat_postgres
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: tomcat
      POSTGRES_USER: dev_account_5456456
      POSTGRES_PASSWORD: dev_password_16545646546546546àèçàç(-çè-à)
    networks:
      - local_tomcat_services
    ports:
      - "6054:5432"

  tomcat:
    container_name: local_tomcat
    image: tomcat:11.0.0-M6-jdk17
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      TOMCAT_USERNAME: maxime
      TOMCAT_PASSWORD: Soleil2020!
    ports:
      - "9090:80"
    networks:
      - local_tomcat_services
    volumes:
      - ./path/to/your/server.xml:/usr/local/tomcat/conf/server.xml
    depends_on:
      - postgres

networks:
  local_tomcat_services:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24